FROM esolang/befunge93

SHELL ["/bin/bash", "-c"]

WORKDIR /app

# Copiez le fichier Befunge dans /app
COPY ./whanos_example_apps/befunge-hello-world/app/main.bf .

# Spécifiez le chemin complet pour le fichier Befunge
CMD ["/root/bef", "./main.bf"]
