FROM gcc:11.2

SHELL ["/bin/bash", "-c"]

WORKDIR /app

COPY ../whanos_example_apps/c-hello-world/app/hello.c .

RUN ls -l /app

COPY ./whanos_example_apps/c-hello-world/Makefile .

RUN make

RUN find . -type f ! -name 'compiled-app' -delete

CMD ./compiled-app
