jenkins:
  systemMessage: "Welcome to Whanos Jenkins Instance!"
  remotingSecurity:
    enabled: true
  securityRealm:
    local:
      allowsSignup: false
      users:
        - name: "Admin"
          id: "admin"
          password: ${ADMIN_PASSWORD}
  authorizationStrategy:
    roleBased:
      roles:
        global:
          - name: "admin"
            description: "Whanos admin"
            permissions:
              - "Overall/Administer"
            assignments:
              - "admin"
  security:
    globalJobDslSecurityConfiguration:
      useScriptSecurity: false

jobs:
  - file: /jenkins/job_dsl.groovy