FROM python:3

WORKDIR /app

COPY ./whanos_example_apps/python-hello-world/requirements.txt requirements.txt

RUN pip install -r requirements.txt

COPY ./whanos_example_apps/python-hello-world/app/ ./app

CMD [ "python3", "-m" , "app"]