FROM python:3

SHELL ["/bin/bash", "-c"]

WORKDIR /app

ONBUILD COPY requirements.txt requirements.txt

ONBUILD RUN pip install -r requirements.txt

ONBUILD COPY ./app ./app

CMD [ "python3", "-m" , "app"]