FROM node:14.17.5

SHELL ["/bin/bash", "-c"]

WORKDIR /app

COPY ./whanos_example_apps/js-hello-world/package.json .
COPY ./whanos_example_apps/js-hello-world/package-lock.json .

# Installez les dépendances avant de copier l'ensemble de l'application
RUN ["npm", "install"]

# Copiez l'ensemble de l'application
COPY ./whanos_example_apps/js-hello-world/app/ ./app/

CMD ["node", "."]
