name: Github Epitech Sync

on: push

jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "git@github.com:yrebia/whanos.git"
          source_branch: "main"
          destination_repo: "git@github.com:EpitechPromo2026/B-DOP-500-NCE-5-1-whanos-yanis.rebia.git"
          destination_branch: "main"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
